openSea:
  apiKeys:
    - ''
    - ''

gcloud:
  queue:
    apiKey: ''
  firestore:
    serviceAccount: |
      {
        "type": "service_account",
        "project_id": "",
        "private_key_id": "",
        "private_key": "",
        "client_email": "",
        "client_id": "",
        "auth_uri": "",
        "token_uri": "",
        "auth_provider_x509_cert_url": "",
        "client_x509_cert_url": ""
      }
alchemy:
  jsonRpc:
    mainNet:
      - ''
      - ''
      - ''
      - ''
    goerli:
      - ''

moralis:
  apiKey: ''

mnemonic:
  apiKey: ''

quickNode:
  wss:
    mainNet:
      - ''

infura:
  ipfs:
    - projectId: ''
      secret: ''
    - projectId: ''
      secret: ''
    - projectId: ''
      secret: ''
